# NOTE: Generated By HttpRunner v3.1.6
# FROM: har/mubu_create_doc.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuCreateDoc(HttpRunner):

    config = Config("testcase description").verify(False)\
        .base_url("https://api2.mubu.com/")\
        .variables(**{"host":"mubu.com"})\
        .variables(**{"phone": "18976231206", "password": "369874125"})

    teststeps = [
        Step(
            RunRequest("/v3/api/user/phone_login")
            .post("/v3/api/user/phone_login")
            .with_headers(
                **{
                    "content-length": "63",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "f3babbb3-056e-4e69-9dcb-638c40d5e311",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {"phone": "$phone", "password": "$password", "callbackType": 0}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.data.id", 487208)
        ),
        Step(
            RunRequest("/app")
            .get("https://${host}/app")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": '"macOS"',
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/home",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1657468223",
                    "SLARDAR_WEB_ID": "70a12b35-2c3a-41b3-a610-7b59dca4b9f1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1657468240",
                    "data_unique_id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "SESSION": "3a7d05a6-95b7-4984-a331-364f3bb4bf63",
                    "reg_entrance": "https%3A%2F%2F${host}%2Fsettings%23",
                    "language": "en-US",
                    "country": "US",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "sec-ch-ua-platform": '"macOS"',
                    "x-request-id": "2281e82c-a038-401c-8e1a-387327e16705",
                    "version": "3.0.0-2.0.0.1824",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/activity/five_years/participation")
            .post("/v3/api/activity/five_years/participation")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "sec-ch-ua-platform": '"macOS"',
                    "x-request-id": "b6d60baa-8dca-439a-9290-c6d219d36a95",
                    "version": "3.0.0-2.0.0.1824",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 4011)
            .assert_equal("body.msg", "unknown error")
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "sec-ch-ua-platform": '"macOS"',
                    "x-request-id": "ba37fd50-a4cc-4447-a957-5e92e2d229dd",
                    "version": "3.0.0-2.0.0.1824",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "3382f848-2c0b-4ffb-b7f5-999a9de906c8",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_string_equals("body.data.documents[0].id", "1dIUNbJps9E") # 添加校验器
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "sec-ch-ua-platform": '"macOS"',
                    "x-request-id": "c1047a9f-9e36-4671-b242-028a3b07ca31",
                    "version": "3.0.0-2.0.0.1824",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_onboard_state")
            .post("/v3/api/user/get_onboard_state")
            .with_headers(
                **{
                    "content-length": "2",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "6aface63-a0b4-4058-8fd6-16548c8e251c",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "8b70dbcb-3629-43f6-a91c-f55a46444379",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "5094dc8e-cef1-48d2-a4d1-1044d41f4450",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "2bb9c39b-25b5-4718-8db9-250d4015c487",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/notify/new_tip/get")
            .post("/v3/api/notify/new_tip/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "2abb0abc-1c5a-42bf-be2a-e51913ba26b7",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "25",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "d60baa30-bb07-40fc-8310-fcc731231f21",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .extract()
            .with_jmespath("body.data.id", "docId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "02d8c3ad-154d-489f-811f-a39ef3a42eb6",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .options("/v3/api/document/edit/get")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "035f2d2c-db00-4fe3-96b9-d44f303b0854",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docId", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .options("/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "94",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "e070e4a7-06bf-422c-a6d4-0029e7e4a111",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "reqId": "1",
                    "type": "USER_HEARTBEAT",
                    "memberId": "3571219694275793",
                    "documentId": "$docId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .options("/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "16df6c07-0dce-4a8d-964c-85cc0d8ee43c",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "a06ae06a-3cdb-4040-95d2-94c6149ac259",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members_v2")
            .options("/v3/api/colla/members_v2")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .options("/v3/api/refer/node/count")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members_v2")
            .post("/v3/api/colla/members_v2")
            .with_headers(
                **{
                    "content-length": "58",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "request-id": "members:3571219694275793:1658026059153",
                    "x-request-id": "9e2aee9a-c3b1-4fab-a5a3-5e6168359c0f",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"memberId": "3571219694275793", "documentId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("/v3/api/refer/node/count")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "version": "3.0.0-2.0.0.1824",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "e1c8176b-622e-4e3d-916a-2d70d08b2b60",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "$docId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "149",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "c0e519ac-11f1-4e9c-af8c-c411568e5213",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "memberId": "3571219694275793",
                    "type": "CHANGE",
                    "version": 0,
                    "documentId": "$docId",
                    "events": [
                        {"name": "nameChanged", "title": "mubu", "original": ""}
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .options("/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://${host}",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "52",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "3e405472-a047-4302-a545-2e50af596797",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docId", "keywords": "mubu", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "250",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "108cbe5e-bee0-4dad-84ca-4a5a74aab1df",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "memberId": "3571219694275793",
                    "type": "CHANGE",
                    "version": 1,
                    "documentId": "$docId",
                    "events": [
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 0,
                                    "parentId": None,
                                    "node": {
                                        "id": "6UcrPdVEE2",
                                        "text": "",
                                        "modified": 1658026062703,
                                        "children": [],
                                    },
                                    "path": ["nodes", 0],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "446",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "2f7d3cd2-18ca-45d5-a3aa-c6d801a7fa18",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "memberId": "3571219694275793",
                    "type": "CHANGE",
                    "version": 2,
                    "documentId": "$docId",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "6UcrPdVEE2",
                                        "text": "<span>1</span>",
                                        "modified": 1658026064390,
                                    },
                                    "original": {
                                        "id": "6UcrPdVEE2",
                                        "text": "",
                                        "modified": 1658026062703,
                                    },
                                    "path": ["nodes", 0],
                                }
                            ],
                        },
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 1,
                                    "parentId": None,
                                    "node": {
                                        "id": "cBJOqgLhr9",
                                        "text": "",
                                        "modified": 1658026064750,
                                        "children": [],
                                    },
                                    "path": ["nodes", 1],
                                }
                            ],
                        },
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "293",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "d6ee0e29-8117-4715-a5c4-462a17010c6d",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "memberId": "3571219694275793",
                    "type": "CHANGE",
                    "version": 3,
                    "documentId": "$docId",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "cBJOqgLhr9",
                                        "text": "<span>2</span>",
                                        "modified": 1658026065424,
                                    },
                                    "original": {
                                        "id": "cBJOqgLhr9",
                                        "text": "",
                                        "modified": 1658026064750,
                                    },
                                    "path": ["nodes", 1],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "250",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "e75156e2-212b-4cf6-b712-b0db3b4fc9a9",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "memberId": "3571219694275793",
                    "type": "CHANGE",
                    "version": 4,
                    "documentId": "$docId",
                    "events": [
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 2,
                                    "parentId": None,
                                    "node": {
                                        "id": "woUUTt0aGj",
                                        "text": "",
                                        "modified": 1658026065790,
                                        "children": [],
                                    },
                                    "path": ["nodes", 2],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "293",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36",
                    "data-unique-id": "88fa8d79-f947-4206-92ad-5cc38f630c6f",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiNDg3MjA4IiwibG9naW5UeXBlIjoibW9iaWxlIiwiZXhwIjoxNjYwNjE4MDQ4LCJpYXQiOjE2NTgwMjYwNDh9.qtFXH-ePHvy6kt5KpXiSZ2c6Zh0JYlTA_kOu375xJTDC2fvRSblLZX_7_i2ZYeiAipRknNBfAJnuX_ZTuncR3w",
                    "x-request-id": "600ac77f-a32c-45a4-8006-5d81e264763d",
                    "sec-ch-ua-platform": '"macOS"',
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "memberId": "3571219694275793",
                    "type": "CHANGE",
                    "version": 5,
                    "documentId": "$docId",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "woUUTt0aGj",
                                        "text": "<span>3</span>",
                                        "modified": 1658026066399,
                                    },
                                    "original": {
                                        "id": "woUUTt0aGj",
                                        "text": "",
                                        "modified": 1658026065790,
                                    },
                                    "path": ["nodes", 2],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreateDoc().test_start()
